### ISSUE TITLE
Do not count photos and @mentions in 140 character count

### ISSUE THREAD

**Issue by rinogo** [twitter/twitter-text#117]
"The social media company will soon stop counting photos and links as part of its 140-character limit for messages, according to a person familiar with the matter." ([Source](http://www.bloomberg.com/news/articles/2016-05-16/twitter-to-stop-counting-photos-and-links-in-140-character-limit))

Will this library be updated to match these changes?

**Comment by rinogo** [comment]
Update: [It's official](https://blog.twitter.com/express-even-more-in-140-characters).  Any thoughts on if and when this library will be updated?  Thanks! :)

**Comment by ran5000** [comment]
any ideas how to handle this changes? are you familiar with other Gems that might already updated for this change?

**Comment by rinogo** [comment]
I haven't looked for other related gems.  However, the library seemed to count characters accurately before, and this change simplifies the system instead of complicating it.  The actual changes are probably actually pretty simple - the more involved part would be putting together updated unit tests.  From what I recall, Twitter is phasing this in for users over the coming months, so it's low-priority for me until it's deployed for everyone.  If at that point Twitter hasn't updated this library, I guess I'll just have to jump in and do it myself. :/

**Comment by wija** [comment]
Is Twitter planning to update this when the new system is rolled out? We have been relying on this for years to provide instant feedback to users on Tweet length and validity as they are creating Tweets. While, as @rinogo commented, tweaking the current code is quite feasible, it would be very nice to be able to keep relying on an official library.

**Comment by andypiper** [comment]
Looking into our plans for this at the moment.

**Comment by twuttke** [comment]
Yes.

I work at Twitter on the tweet composer and the upcoming changes that were
announced. We use this library as well in our own products, including the
Twitter service that rejects tweets when they are too long.

I'm not sure what date exactly, but the library will get updated to do the
correct thing.

Tom

**Comment by brianc-sprout** [comment]
Any idea when this update will go live?

**Comment by twuttke** [comment]
According to https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

The rules of tweet text counting are still the same, they don't automatically give you back characters unless you change the way you create the tweet when you call status/update. Specifically,
1. If your app attaches images using media_ids param instead of injecting urls in the tweet text, then you won't pay a 24 char penalty anymore (when available)
2. Your app can inject a quote tweet (retweet with comment) using attachment_url param (when available) instead of adding a tweet's link, so it would not count against 140. Note you can't do two attachments, you either have media_ids or attachment_url. 
3. If your app strips leading @mentions from the beginning of the status and instead relies on the auto_populate_reply_metadata param + in_reply_to_status_id param to generate up to 50 implicit reply mentions at the beginning of the extended tweet (when available) then the auto generated reply names don't count against your 140. 

What is not changing - any @mentions or links you place in the status text will still be counted against 140 like always. The only way to get the benefit is to use the new metadata params. 

twitter-text is more about calculating the length of the status part of the tweet, not the tweet + optional prefixes and attachments. So I don't know that we need to change anything in this library. Do you have any suggestions after reading that document?

Notice I said when available in every case - these new modes are not enabled yet. I don't know the launch plan exactly, stay tuned. I just want to you be aware that twitter-text probably won't need to be changed to accommodate this.

**Comment by brianc-sprout** [comment]
My understanding of that doc is that if I want to send a regular tweet (not a reply/DM) with **@mentions** at the start of my update, I will just add those mentions at the start of my text and send them. There is no talk in that doc of another param for **@mentions**. So what you are saying is I need to preprocess my message before I send it to twitter-text?

**Comment by twuttke** [comment]
The changes do not affect creating an original tweet with @mentions in it. You would still do that the same way as today. It only adds an alternate way you can prepend up to 50 users in a reply without losing characters.

If you want to prepend any @mentions to the beginning of an original tweet, they count against the 140 and you may as well use twitter-text to count them as you would today.

**Comment by andypiper** [comment]
@brianc-sprout if you are creating a new Tweet, then @mentions (at the beginning of the Tweet or anywhere else inside it) will count towards 140.

If you reply-to an existing Tweet (note that the Tweet **must still exist** or the status update will fail), **and** supply the new `auto_populate_reply_metadata` value, then any existing @mentions will be moved out of the 140 on the server side. You are still limited to 140 characters, including any new @mentions you may add to the new text.

Currently I'm inclined to agree with @twuttke that twitter-text may not need significant updates since the way we handle link shortening etc will be the same, the `text` value handed to `statuses/update` will continue to be 140 characters even if the underlying value in resulting Tweet object may end up larger due to @mentions prepended on the server side, and the trailing media or attachment URL.

We will continue to work with the community and share any updates if we make them internally around this library, but we don't have specific dates to share at this stage.

**Comment by rinogo** [comment]
Thanks for your insights and the helpful discussion, everyone!

I think I agree with @twuttke and @andypiper - this library may not be the right place to solve this problem.  The task of separating a Tweet's text from the associated metadata (e.g. `media_ids`, `auto_populate_reply_metadata`, and `in_reply_to_status_id`) is not the responsibility of this library.

For those of us maintaining legacy apps (or building new ones), it might be useful to highlight what seems to be a philosophical shift at Twitter.  In the distant past, a Tweet was seen as a string of raw text (often supplied via SMS) that Twitter would parse to add extra functionality to - adding links for `@mention`s, hashtags, URLs, etc.  It seems that these changes (and the "near future" changes with `attachment_url`) continue the trend of moving away from "raw text" typed in by the user and instead favoring "raw text" *with associated metadata*.  While this may seem obvious, the implication is that we should likely be designing/upgrading our apps with separate UI elements to acquire media URLs, the attachment URL, etc.

**Comment by brianc-sprout** [comment]
Thanks @twuttke and @andypiper . I had read an earlier form of their doc and it was nebulous where all the new **@mentions** fit in. The most recent doc makes it much clearer that it is only for replies.

**Comment by andypiper** [comment]
(NB I was the author of the doc, so can only apologize for any confusion!) 😄

**Comment by rinogo** [comment]
@andypiper - I'm not sure if you were the same one who made the updates to the original doc, but regardless, thanks to whomever added the bit hinting about the similar "near future" changes with `attachment_url`.  Very helpful to have a longer-term vision of where the API is headed.
