### ISSUE TITLE
modifyIndicesFromUnicodeToUTF16 internal API?

### ISSUE THREAD

**Issue by thisconnect** [twitter/twitter-text#119]
I wrote a script that converts a tweet to markdown and ran into unicode problems. With modifying the indices by `{ modifyIndicesFromUnicodeToUTF16 } from 'twitter-text'` everything works correctly, but I am concerned that this method is internal API.

BTW the package.json still points to https://github.com/twitter-archive/twitter-text-js 
Should point to https://github.com/twitter/twitter-text/tree/master/js
https://www.npmjs.com/package/twitter-text

**Comment by thisconnect** [comment]
@codemonkey3045 why was this closed?

**Comment by codemonkey3045** [comment]
It should be okay for you to use modifyIndicesFromUnicodeToUTF16. It relies on IndexConverter and that's defined in this library too https://github.com/twitter/twitter-text/blob/cf3b20a330e1c53ef873ae780d2461bfc6babcef/java/src/com/twitter/Extractor.java#L508

I've noted the package.json being outdated and will get those repo links fixed in version 1.14.3 that I hope to get out in January. Thanks for pointing those out! It's easy to forget to update those. 

Could you elaborate a bit about the unicode problems you've faced, if this is still an issue you'll like to reopen? I went through a bit of a rough clean up issues marathon yesterday. Sorry about that.

**Comment by thisconnect** [comment]
Thanks a lot!! All good!

modifyIndicesFromUnicodeToUTF16 Fixes all my unicode problems. I was just concerned that it is internal api. 

Thanks for your quick reply.
