### ISSUE TITLE
Some links, when shortened, are longer than the original link.

### ISSUE THREAD

**Issue by GeorgeWL** [twitter/twitter-text#140]
A perfect example is https://qntm.org/twit (which is a relatively old article about this exact problem) is a link which is 21 characters long, 22 if you fancy a trailing slash. 

But when posted to Twitter and the twitter link shortener transforms it, the link becomes 23 characters long, **making the shortened link Longer than the original link.**

I think the most obvious solution would simply be that if twitter recognizes a link shorter than the shortened link, it posts that without any shortening applied.

There are far shorter links than the e.g gave too, like links from http://v.ht are at most 16 characters long, yet twitter still "shortens" them to 22 characters long.

It's only mildly annoying, but it still shouldn't happen, those who've spent the money in getting a very short domain should be able to reap the benefits of having very short links.

# And this has been an issue since 16th August 2011 at the very least, though it's probably older.

**Comment by andypiper** [comment]
Understand the reasoning behind this ticket, however per the [documentation on our t.co shortener](https://dev.twitter.com/overview/t.co):

> Wrapping these shared links helps Twitter protect users from malicious content while offering useful insights on engagement. All links submitted within tweets and direct messages, regardless of length, will eventually be wrapped with t.co.

I don't believe there's any plan to change this approach, and (very broadly speaking) it will only affect a small number of shared links. Also note that in the future, links attached to Tweets via the attachment_url parameter, will cease to count towards the 140 limit.

**Comment by twuttke** [comment]
Before people infer too much from this thread, I confirmed that
attachment_url will not accept arbitrary urls. It is for links to other
tweets and possibly a few other Twitter internal links. Maybe this will
change in the future, but probably not in the short term.

As far as t.co being a link shortener, I think of it more as a link
tokenizer.

On Aug 30, 2016 10:21 AM, "Andy Piper" <notifications@github.com> wrote:

Understand the reasoning behind this ticket, however per the documentation
on our t.co shortener <https://dev.twitter.com/overview/t.co>:

Wrapping these shared links helps Twitter protect users from malicious
content while offering useful insights on engagement. All links submitted
within tweets and direct messages, regardless of length, will eventually be
wrapped with t.co.

I don't believe there's any plan to change this approach, and (very broadly
speaking) it will only affect a small number of shared links. Also note
that in the future, links attached to Tweets via the attachment_url
parameter, will cease to count towards the 140 limit.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/twitter/twitter-text/issues/140#issuecomment-243513761>,
or mute the thread

**Comment by jnievelt** [comment]
I agree with the responses here but would offer that it probably affects many links shared on Twitter.  Many users (businesses especially) will employ their own (first party or third party) shortener/tokenizer, presumably because:

* Twitter still shows the original links in many cases (and truncated links are a little messy)
* They may want to change where links redirect to
* They may want to monitor the clicks via the redirect links

**Comment by Georgiel** [comment]
Yeah stuff like bit.ly links which have built-in analytics

**Comment by johannesnagl** [comment]
This library has nothing to do with how twitter.com (or the api) is working. I think everyone can understand that it makes sense to shorten every link (not only links which are longer then the t.co links). 

this is not something the twitter-text repo can change. so I would simply close this issue.

**Comment by GeorgeWL** [comment]
@johannesnagl where would you say it should be placed?

**Comment by johannesnagl** [comment]
i don't think that case should be handled at all. as I said: twitter is doing the right thing to shorten ALL links and not only links longer then their url shortener.

I'm not affiliated with Twitter, but I would argue this is a "won't fix".
