### ISSUE TITLE
isInvalidTweet doesn't allow for new tweet length counting rules

### ISSUE THREAD

**Issue by timhaines** [twitter/twitter-text#143]
Tweets with 140 characters + url are now valid.  The isInvalidTweet method (in javascript at least) will say these tweets are invalid.

**Comment by twuttke** [comment]
The 140 characters should not be combined with a url as a single text item in the composer. Please read https://dev.twitter.com/overview/api/upcoming-changes-to-tweets carefully. 

In order to create a new extended tweet, a composer needs to keep the text separate from the attachment url or media objet. And the url can only be a quote tweet or dm deep link, not an arbitrary url.

**Comment by twuttke** [comment]
Clarification: You CAN still mix urls and text like before. Any urls in the text will still be tokenized into 23 chars. What I wanted to emphasize was that the only way to get a tweet with 140 chars in addition to an attachment is to keep the attachment metadata separate from the tweet text.

**Comment by timhaines** [comment]
Oh.  That is weird.  A link to a tweet at the end of a tweet still counts as 23 chars, unless the 'quote tweet' mechanism is used.  On the server it's adjusted to function the same as a quote tweet though right?

**Comment by timhaines** [comment]
@twuttke Thanks for the clarification.  This seems a little odd, but your instructions in that link do make sense.  Closing this issue.

FWIW, attachment_url should prob be added to https://dev.twitter.com/rest/reference/post/statuses/update now right?

**Comment by andypiper** [comment]
I'll be adding the new parameters to the relevant API endpoint docs in the near future.
