### ISSUE TITLE
getTweetLength should (have option to) ignore @mentions

### ISSUE THREAD

**Issue by rasmusbp** [twitter/twitter-text#182]
**Background**
As per [recent update](https://blog.twitter.com/en_us/topics/product/2017/now-on-twitter-140-characters-for-your-replies.html) from Twitter, mentions will no longer count towards the Tweet’s 140 characters.

**Change request**
By either changing the default behaviour of the method or via an option property (i.e. `options.ignore_mentions`), `getTweetLength` should not include mentions when calculating the length of passed text.

Whatever makes sense in respect to this being a potential breaking change for consumers of twitter-text.

**Comment by rasmusbp** [comment]
Thanks for picking this up 😃 .

**Comment by twuttke** [comment]
this issue has been brought up several times and each time it has been
closed by the explanation given here:
https://github.com/twitter/twitter-text/issues/117

what has changed since then?

Last I heard, Twitter still counts the @mentions in the 140 character
counter unless the Tweet is in reply to an existing Tweet *and* auto
populate reply mentions is enabled. And in that case, the sender is
expected to not prepend @mentions from the in reply to Tweet, since they
get added automatically by the server in that case. Any new @mentions added
in the reply are still counted against 140.

Tom
