### ISSUE TITLE
Emojis are not properly counted

### ISSUE THREAD

**Issue by gwidonw** [twitter/twitter-text#203]
Take as an example "Hand from back with index finger pointing right" emoji 👉

* When you use `getTweetLength` it is counted as 1 character
* But when you add this emoji directly into twitter.com tweet editor it is counted as 2 characters

Same problem can be found with multiple other emojis. As an example: 👩‍💻👨‍💻 are counted as 5 characters each by Twitter.com and 3 characters each by getTweetLength

It can be easily reproduced here: 
https://npm.runkit.com/twitter-text
```
var twitterText = require("twitter-text")

var text = "👉"

var tweetLength = twitterText.getTweetLength(text)
var jsLength = text.length

var response = `getTweetLength: ${tweetLength}, jsLength ${jsLength}`
```

**Comment by summera** [comment]
@gwidonw have you found a pattern and/or fix with the emoji counting? I'm running into this issue as well.

**Comment by summera** [comment]
Adding another test case here:

Twitter reports 👨🏾‍⚖️ as `9` characters while Javascript's `.length` returns `7`
```javascript
"👨🏾‍⚖️".length
=> 7
```

**Comment by clementEchobox** [comment]
Running into this issue as well

**Comment by adrlen** [comment]
Did you update the lib to 2.x ?

**Comment by summera** [comment]
Upgrading to `2.0.2` fixed the issue for me

**Comment by kaushlakers** [comment]
@gwidonw @clementEchobox please update to the latest version as @adrlen suggested to get parity with what you are seeing on twitter.com.

**Comment by kaushlakers** [comment]
As an additional note, I figured I'd add some details here about how emoji are actually counted and ref the same comment in future issues that might be created around the same theme. 

Just for context, twitter-text has never counted ALL emoji as 1 character even before 280. It was always **the number of codepoints** associated with the emoji. Only basic emojis like 😃 or 😁 were counted as 1.

**Before 280:**
😃 === 1 character
👨‍👩‍👧‍👦 === 7 characters (because 7 codepoints)

**Note:** *No of codepoints !== javascript length*

With the new counting scheme, 280 does not mean just 280 characters. We call it a "weighted count" of 280. Details about our counting scheme are mentioned [here](https://developer.twitter.com/en/docs/developer-utilities/twitter-text) in our official documentation.

Here is the [counting configuration](https://github.com/twitter/twitter-text/tree/master/config) that twitter-text uses internally. This defines the character ranges and their respective weights. Note that the "defaultWeight" is 200.

```js
{
  "version": 2,
  "maxWeightedTweetLength": 280,
  "scale": 100,
  "defaultWeight": 200,
  "transformedURLLength": 23,
  "ranges": [
    {
      "start": 0,
      "end": 4351,
      "weight": 100
    },
    {
      "start": 8192,
      "end": 8205,
      "weight": 100
    },
    {
      "start": 8208,
      "end": 8223,
      "weight": 100
    },
    {
      "start": 8242,
      "end": 8247,
      "weight": 100
    }
  ]
}
```
If you look at codepoints for emojis, you will realize that they fall outside any of the ranges defined with a weight of 100. Hence emojis which used to be counted as 1 before, now count for 2. Another point to note is that the [ZWJ](https://emojipedia.org/zero-width-joiner/), which is used to join composite emojis together is also discounted with a weight of 100.
So let's revisit the counts now:

**After 280:**
😃 === 2 weighted characters
👨‍👩‍👧‍👦 === 11 weighted characters (4 emojis * 2 + 3 ZWJs = 11)

Hope this made things a little more clear.

We are totally aware of these inconsistencies with our counting and we have a plan to implement a better way of parsing emojis in twitter-text. We're planning to work on this soon. :)

**Comment by spark911** [comment]
Good to hear you're going to improve it further. Given the recent release of Tweet storm I'm not too sure why I can't just send you a single string of text and let you figure out how long it is and how many Tweets to represent it as ;)

**Comment by kaushlakers** [comment]
Closing due to no update from the issue author.
