### ISSUE TITLE
Parser do not support validation for replies (don't count mentions and links)

### ISSUE THREAD

**Issue by grubinohyp3r** [twitter/twitter-text#230]
Hi,
I tried the tool in the case of validating a reply tweet.

As it's mentioned in **Simplified replies and media attachments** ( https://developer.twitter.com/en/docs/tweets/tweet-updates ) :
_@names that auto-populate at the start of a reply Tweet will not count towards the character limit (but new non-reply Tweets starting with a @mention will count, as will @mentions added explicitly by the user in the text body of the Tweet)._

The parser in this case (for Javascript), always count the number of characters. It doesn't remove the '@user' or 'links' for validate.

It doesn't have any configuration, in this case, to specify that the message is a 'reply'.

Any help will be really appreciated! 

Using: Javascript - Version : 2.0.2

**Comment by andypiper** [comment]
Thanks. twitter-text is about tokenizing and validating the content of the status message. The statuses/update Twitter API endpoint provides explicit methods (`auto_populate_reply_metadata` and `attachment_url`) which exclude the replies and URLs if possible and appropriate. We've [previously stated](https://github.com/twitter/twitter-text/issues/117) that it is not appropriate to do this work inside the twitter-text library.

We can make this more explicit in the documentation as an enhancement, but there are no plans to change this otherwise.

Closing as wont-fix and working as designed.

**Comment by grubinohyp3r** [comment]
Great @andypiper ! Thanks for the clarification!  👍
