### ISSUE TITLE
localhost should be considered a valid domain

### ISSUE THREAD

**Issue by benbeadle** [twitter/twitter-text#43]
Somewhat similar to #40, `localhost` should be considered a valid domain.

For example:

> http://**localhost**/
> or
> http://**localhost**:8080/

However, the following code

```
twttr.txt.extractUrls("http://localhost/example");
```

returns `[]`.

**Comment by twuttke** [comment]
Why would we want people Tweeting urls that only work on their own machines? Twitter crawls every url to determine if it is not spam and then shortens it. This sounds like a security issue.

Do you have an example of why this might be needed?

**Comment by benbeadle** [comment]
I suppose I wasn't limiting the library to only Twitter, but viewing it as a library one could use in other cases/applications to check the true/complete validity of a URL.

I, of course, use localhost for development, but if this is more of a library to validate a URL that should be publicly available - then localhost shouldn't be added.

**Comment by twuttke** [comment]
Ok I see why you suggested it then.

But this is a twitter-specific library. The question it is authoritatively answering is  - what spans of text in a Tweet would be marked as clickable urls by the official Twitter apps. Twitter already extends http://www.ietf.org/rfc/rfc2396.txt a little -- one example is an underscore in sub-domains. http://a_b.example.com is not a valid url but Twitter added it as an exception just because users kept trying to use it and browsers were all allowing it. The url validator that we use from apache commons is very strict http://answer.techwikihow.com/706260/exactly-does-apache-commons-urlvalidator.html

I was going to point you towards a more generic plain text linkifier that isn't specific to Tweets but I couldn't find anything that was all that good or universal.
