### ISSUE TITLE
twitterText.extract() are't extract some links correctly

### ISSUE THREAD

**Issue by ArtemNikolaev** [twitter/twitter-text#88]
Problem occurs, when i try to extract from string link to youtube playlist, like it:

```
https://www.youtube.com/watch?v=f1DVxtjiBc4&feature=youtu.be&list=PLMBnwIwFEFHeaOuHqSEpZPhcFkRSrunE-
```

plugin can't see the last character `-`, so i can see video, but playlist for this video isn't shown.
When i try do the same thing on Twitter, i see the same picture^

```
https://www.youtube.com/watch?v=f1DVxt…-
```

link shortener can't see `-`.

Thank you for response

**Comment by erilyth** [comment]
I think this error only occurs in the js version, so this could be a potential fix.

**Comment by pioul** [comment]
I'd also be curious to learn about the library's view on this, since looking at those two sets of valid characters, not including dashes as valid query ending chars looks deliberate: https://github.com/twitter/twitter-text/blob/master/js/twitter-text.js#L243-L244

If I'm reading the URI RFC correctly, "-" does look like a valid query ending character

**Comment by mattkauffman23** [comment]
Curious why this issue was closed. Its impacting the app I'm working on as well. Same case as above: urls pointing to youtube playlists ending in `-`.

**Comment by codemonkey3045** [comment]
I'll try to get a final decision this week on allowing - as the end character. Twitter's strict 140 character limit might lead some people to type "example.com- great website blah..." and that'll be a broken link.

**Comment by leeaustinadams** [comment]
Appears to be fixed in latest
